[project]
name = "lupin"
version = "0.1.0"
description = "월급루팡 게임 웹사이트 - 직장에서 몰래 할 수 있는 게임들"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "jinja2>=3.1.2",
    "python-multipart>=0.0.6",
    "websockets>=12.0"
]
